# Generated by Django 4.2.9 on 2024-08-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='status',
            field=models.CharField(blank=True, default='creating', max_length=20, null=True),
        ),
    ]
