# Generated by Django 4.2.9 on 2024-09-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='cycle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
