# Generated by Django 4.2.9 on 2024-10-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_invoiceline_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='vps_auto_archive',
            field=models.IntegerField(default=0),
        ),
    ]
