# Generated by Django 4.2.9 on 2024-08-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vps_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
