# Generated by Django 4.2.9 on 2024-10-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_appsetting_vps_auto_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='vps_refund_hours',
            field=models.IntegerField(default=0),
        ),
    ]
