# Generated by Django 4.2.9 on 2024-08-27 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_vps_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPSLog',
            fields=[
                ('id', models.CharField(default=home.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('_deleted', models.BooleanField(default=False)),
                ('action', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vps')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
