# Generated by Django 4.2.9 on 2024-10-05 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_appsetting_vps_refund_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.CharField(default=home.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('_deleted', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=200)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.vps')),
            ],
            options={
                'db_table': 'refund_request',
            },
        ),
    ]
