# Generated by Django 4.2.9 on 2024-08-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_vpslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpslog',
            old_name='performed_by',
            new_name='user',
        ),
    ]
