# Generated by Django 4.2.9 on 2024-08-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_vpslog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpslog',
            name='hostname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vpslog',
            name='performed_by',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
