# Generated by Django 4.2.9 on 2024-10-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_unpaidorderreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='group_locked_config',
            field=models.JSONField(default=dict),
        ),
    ]
