# Generated by Django 4.2.9 on 2024-08-28 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_vpslog_hostname_vpslog_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
