# Generated by Django 4.2.9 on 2024-10-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_appsetting_group_locked_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='region',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
