# Generated by Django 4.2.9 on 2024-11-05 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cryptotransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptotransaction',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='payment_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Paid'), ('U', 'Unknown'), ('C', 'Canceled')], default='P', max_length=200),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
