# Generated by Django 4.2.9 on 2024-11-07 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_cryptotransaction_raw_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeTransaction',
            fields=[
                ('id', models.CharField(default=home.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('_deleted', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='USD', max_length=200)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Paid'), ('U', 'Unknown'), ('C', 'Canceled')], default='P', max_length=200)),
                ('description', models.TextField()),
                ('payment_id', models.CharField(max_length=200, unique=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stripe_transaction',
            },
        ),
    ]
