# Generated by Django 4.2.9 on 2024-11-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_stripetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='display_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
