# Generated by Django 4.2.9 on 2024-08-28 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_invoice_invoiceline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='home.transaction'),
        ),
    ]
