# Generated by Django 4.2.9 on 2024-11-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_invoice_display_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='display_text',
        ),
    ]
