# Generated by Django 4.2.9 on 2024-12-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_invoice_display_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='creation_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='status',
            field=models.CharField(default='open', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='vps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='home.vps'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('expired', 'Expired'), ('unread', 'Unread')], default='unread', max_length=200),
        ),
    ]
