# Generated by Django 4.2.9 on 2024-12-07 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_vps_creation_data_alter_invoiceline_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCounter',
            fields=[
                ('id', models.CharField(default=home.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('_deleted', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict)),
                ('type', models.CharField(choices=[('VPS', 'VPS')], default='VPS', max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
