# Generated by Django 4.2.9 on 2024-08-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_end_date_vps_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
