# Generated by Django 4.2.9 on 2024-12-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_systemcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attached_invoice',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attached_vps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
