# Generated by Django 4.2.9 on 2024-08-30 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_invoice_cycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vps',
            old_name='os',
            new_name='os_version',
        ),
    ]
