# Generated by Django 4.2.9 on 2025-02-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_ticket_attached_invoice_ticket_attached_vps'),
    ]

    operations = [
        migrations.CreateModel(
            name='VNCSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('host', models.CharField(max_length=200)),
                ('session_key', models.CharField(max_length=200, unique=True)),
                ('vnc_link', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnc_sessions', to='home.vps')),
            ],
            options={
                'db_table': 'vnc_session',
            },
        ),
    ]
