# Generated by Django 4.2.9 on 2024-08-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_os_vps_os_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='os',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
