# Generated by Django 4.2.9 on 2025-02-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_vncsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vncsession',
            name='host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vncsession',
            name='port',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
