# Generated by Django 4.2.9 on 2025-02-23 05:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_vncsession_host_alter_vncsession_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='vncsession',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 12, 16, 38, 709659)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vncsession',
            name='vps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnc_sessions', to='home.vps', unique=True),
        ),
    ]
