# Generated by Django 4.2.9 on 2025-02-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_vncsession_expired_at_alter_vncsession_vps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vncsession',
            name='expired_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
