# Generated by Django 4.2.9 on 2024-08-30 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_ticket_ticketchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketchat',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='home.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketchat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
