# Generated by Django 4.2.9 on 2025-02-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='last_resend_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
