# Generated by Django 4.2.9 on 2024-09-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
