# Generated by Django 4.2.9 on 2024-09-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_user_balance_amount_user_total_paid_user_total_topup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='identifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
