# Generated by Django 4.2.9 on 2024-09-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_paypaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypaltransaction',
            name='payment_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
