# Generated by Django 4.2.9 on 2024-09-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_transaction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypaltransaction',
            name='token',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
