# Generated by Django 4.2.9 on 2024-09-15 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_paypaltransaction_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='cycle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='TriggeredOnceEvent',
            fields=[
                ('id', models.CharField(default=home.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('_deleted', models.BooleanField(default=False)),
                ('event_name', models.CharField(blank=True, choices=[('VPS_EXPIRED', 'VPS Expired')], max_length=200, null=True)),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
                ('vps_id', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
