# Generated by Django 4.2.9 on 2024-09-16 18:05

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_vps_cycle_triggeredonceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.CharField(default=home.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('_deleted', models.BooleanField(default=False)),
                ('invoice_due_days', models.IntegerField(default=3)),
                ('sufficient_balance_suspend_days', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='triggeredonceevent',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='triggeredonceevent',
            name='event_name',
            field=models.CharField(blank=True, choices=[('VPS_EXPIRED', 'VPS Expired'), ('INVOICE_EXPIRED', 'Invoice Expired'), ('INVOICE_SUSPENDED', 'Invoice Suspended')], max_length=200, null=True),
        ),
    ]
