# Generated by Django 4.2.9 on 2024-09-18 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_appsetting_triggeredonceevent_invoice_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.CharField(default=home.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(auto_now_add=True)),
                ('_updated', models.DateTimeField(auto_now=True)),
                ('_deleted', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='VND', max_length=200)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Paid'), ('C', 'Canceled'), ('U', 'Undefined')], default='P', max_length=200)),
                ('description', models.TextField()),
                ('gateway', models.CharField(choices=[('BIDV', 'BIDV'), ('VIETCOMBANK', 'Vietcombank'), ('TECHCOMBANK', 'Techcombank')], default='BIDV', max_length=200)),
                ('payment_id', models.CharField(max_length=200)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
