# Generated by Django 4.2.9 on 2024-09-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
    ]
