# Generated by Django 4.2.9 on 2024-09-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_vps_auto_renew'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_ticket',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
