# Generated by Django 4.2.9 on 2024-09-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_user_open_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='backup_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vps',
            name='log_count',
            field=models.IntegerField(default=0),
        ),
    ]
