# Generated by Django 4.2.9 on 2024-09-22 18:51

from django.db import migrations, models
import utils.random_thing


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_vps_backup_count_vps_log_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_code',
            field=models.CharField(blank=True, default=utils.random_thing.generate_customer_code, max_length=200, null=True),
        ),
    ]
