# Generated by Django 4.2.9 on 2024-09-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_user_customer_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='appsetting',
            table='app_setting',
        ),
        migrations.AlterModelTable(
            name='balance',
            table='balance',
        ),
        migrations.AlterModelTable(
            name='banktransaction',
            table='bank_transaction',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoice',
        ),
        migrations.AlterModelTable(
            name='invoiceline',
            table='invoice_line',
        ),
        migrations.AlterModelTable(
            name='paypaltransaction',
            table='paypal_transaction',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
        migrations.AlterModelTable(
            name='ticketchat',
            table='ticket_chat',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
        migrations.AlterModelTable(
            name='triggeredonceevent',
            table='triggered_once_event',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='usertoken',
            table='user_token',
        ),
        migrations.AlterModelTable(
            name='vps',
            table='vps',
        ),
        migrations.AlterModelTable(
            name='vpslog',
            table='vps_log',
        ),
    ]
